import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { autosecBranchName } from './triage.js';

const exec = promisify(execFile);

/**
 * Branch, commit, push, and open a PR. Returns { url, branch, draft }.
 */
export async function openPR({ repoDir, vuln, ctx, summary, testResult, baselineResult, branchBase, draft, push = true, verdict }) {
  const branch = autosecBranchName(vuln);
  const title = `autosec: bump ${vuln.package} to ${vuln.fixed} (${vuln.severity})`;
  const body = renderBody({ vuln, ctx, summary, testResult, baselineResult, verdict });

  await git(repoDir, ['checkout', '-B', branch]);
  await git(repoDir, ['add', '-A']);
  // No-op commit guard
  try {
    await git(repoDir, ['diff', '--cached', '--quiet']);
    return { url: null, branch, draft, note: 'no changes to commit' };
  } catch {
    // there are staged changes — proceed
  }
  await git(repoDir, ['commit', '-m', title]);

  if (!push) {
    const { stdout: diff } = await git(repoDir, ['diff', '--stat', `${branchBase}..HEAD`]);
    return {
      url: null,
      branch,
      draft,
      pushed: false,
      title,
      body,
      diffstat: diff.trim(),
      workspace: repoDir,
      note: 'push skipped (--no-push); branch committed locally',
    };
  }

  try {
    await git(repoDir, ['push', '-u', 'origin', branch, '--force-with-lease']);
  } catch (e) {
    const msg = `${e.message}\nstderr: ${e.stderr || ''}\nstdout: ${e.stdout || ''}`;
    throw new Error(`git push failed: ${msg}`);
  }

  const args = [
    'pr', 'create',
    '--title', title,
    '--body', body,
    '--base', branchBase,
    '--head', branch,
  ];
  if (draft) args.push('--draft');

  const { stdout } = await exec('gh', args, { cwd: repoDir });
  const url = (stdout.match(/https:\/\/\S+/) || [])[0] || null;

  if (draft) {
    try {
      await exec('gh', ['pr', 'edit', branch, '--add-label', 'autosec,needs-human'], { cwd: repoDir });
    } catch {}
  } else {
    try {
      await exec('gh', ['pr', 'edit', branch, '--add-label', 'autosec'], { cwd: repoDir });
    } catch {}
  }

  return { url, branch, draft };
}

async function git(cwd, args) {
  return exec('git', args, { cwd });
}

function renderBody({ vuln, ctx, summary, testResult, baselineResult, verdict }) {
  const tail = (testResult?.output || '').split('\n').slice(-60).join('\n');
  const baselinePassed = baselineResult?.pass ?? true;
  const verdictLabel = verdict?.label || (testResult?.pass ? 'pass' : (baselinePassed ? 'regression' : 'pre-existing-failure'));
  const verdictNote = {
    pass:                   'PASSED',
    regression:             'FAILED (regression introduced by this bump)',
    'pre-existing-failure': 'FAILED (pre-existing failures — baseline also failing)',
    'environment-broken':   'FAILED (test environment broken — not caused by this bump)',
  }[verdictLabel] || 'FAILED';
  const testNote = verdictNote;
  const meta = ctx.repoMeta;
  const repoLink = meta ? `https://github.com/${meta.owner}/${meta.repo}` : null;
  return [
    `## AutoSec dependency bump`,
    ``,
    `- **Package:** \`${vuln.package}\``,
    `- **Bump:** \`${vuln.current || '?'}\` → \`${vuln.fixed}\``,
    `- **Severity:** ${vuln.severity}`,
    `- **Major version bump:** ${vuln.isMajorBump ? 'yes' : 'no'}`,
    vuln.advisoryUrl ? `- **Advisory:** ${vuln.advisoryUrl}` : null,
    repoLink ? `- **Upstream:** ${repoLink}` : null,
    ``,
    `### Migration notes (from agent)`,
    ``,
    summary?.migration_notes || '(none)',
    ``,
    `### Files touched`,
    ``,
    (summary?.files_touched || []).map((f) => `- \`${f}\``).join('\n') || '(see diff)',
    ``,
    `### Changelog source`,
    ``,
    `${ctx.changelog.source} — ${ctx.changelog.notes}`,
    ``,
    `### Test results`,
    ``,
    `- **Baseline (pre-fix):** ${baselinePassed ? 'PASSED' : 'FAILED'}`,
    `- **Post-fix:** ${testNote}`,
    verdict?.reason ? `- **Verdict reason:** ${verdict.reason}` : null,
    verdict?.hint ? `- **Hint:** ${verdict.hint}` : null,
    ``,
    `### Test output (tail)`,
    ``,
    '```',
    tail || '(no output captured)',
    '```',
    ``,
    `---`,
    `_Generated by AutoSec. Status: **${summary?.status || 'unknown'}**_`,
  ]
    .filter((x) => x !== null)
    .join('\n');
}
